version: 2.1

orbs:
  # This uses the iOS Orb located at https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@0.0.25

workflows:
  test_and_validate:
    jobs:
      - ios/test:
          name: Unit Tests
          xcode-version: "10.2.0"
          workspace: WordPressUI.xcworkspace
          scheme: WordPressUI
          device: iPhone XS
          ios-version: "12.2"
          bundle-install: false
          pod-install: false
      - ios/test:
          name: UI Tests
          xcode-version: "10.2.0"
          workspace: WordPressUI.xcworkspace
          scheme: Example
          device: iPhone XS
          ios-version: "12.2"
          bundle-install: false
          pod-install: false
      - ios/validate-podspec:
          name: Validate Podspec
          xcode-version: "10.2.0"
          podspec-path: WordPressUI.podspec
